//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEstadisticas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebRequestsDynatraceSemana
    {
        public int ID { get; set; }
        public string URI { get; set; }
        public string Canal { get; set; }
        public float TasaFallo { get; set; }
        public float Numero { get; set; }
        public int Semana { get; set; }
        public int Anyo { get; set; }
        public int NumDiasActividad { get; set; }
    }
}
