

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GeneracionEstadisticasDynatrace
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DATA_DYNAEntities : DbContext
{
    public DATA_DYNAEntities()
        : base("name=DATA_DYNAEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<DatosDynatrace> DatosDynatrace { get; set; }

    public virtual DbSet<DatosDynatraceMes> DatosDynatraceMes { get; set; }

    public virtual DbSet<DatosDynatraceSemana> DatosDynatraceSemana { get; set; }

    public virtual DbSet<WebRequestsDynatrace> WebRequestsDynatrace { get; set; }

    public virtual DbSet<WebRequestsDynatraceMes> WebRequestsDynatraceMes { get; set; }

    public virtual DbSet<WebRequestsDynatraceSemana> WebRequestsDynatraceSemana { get; set; }

    public virtual DbSet<WS_END> WS_END { get; set; }

}

}

