
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GeneracionEstadisticasDynatrace
{

using System;
    using System.Collections.Generic;
    
public partial class DatosDynatraceMes
{

    public int ID { get; set; }

    public string Metrica { get; set; }

    public string Canal { get; set; }

    public float Excepciones { get; set; }

    public float Promedio { get; set; }

    public float Percentil95 { get; set; }

    public float NumPromedio { get; set; }

    public float NumPercentil { get; set; }

    public int Mes { get; set; }

    public int NumDiasActividad { get; set; }

    public int Anyo { get; set; }

}

}
