
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GeneracionEstadisticasDynatrace
{

using System;
    using System.Collections.Generic;
    
public partial class WS_END
{

    public int ID { get; set; }

    public string WS_ID { get; set; }

    public string WS_NOMBRE { get; set; }

    public string ENDPOINT { get; set; }

    public string ACCION { get; set; }

    public string ESTADO { get; set; }

}

}
